== OrthoMCLClient

**:warning: THIS REPO HAS BEEN DEPRECATED :warning:**

Client code has been moved to https://github.com/VEuPathDB/web-monorepo

=== Description

`OrthoMCLClient` is an extension of the [WDKClient](https://github.com/VEuPathDB/WDKClient) for the [OrthoMCL project](https://orthomcl.org/orthomcl/about.do). As with the `WDKClient`, `OrthoMCLClient` is React-based and mostly written in [TypeScript](https://www.typescriptlang.org/) and SCSS
([Sass](https://sass-lang.com/)).

(Note: [OrthoMCLService](https://github.com/VEuPathDB/OrthoMCLService) provides the associated service.)


=== Installation and Usage

Presently, `OrthoMCLClient` should be installed following the [Strategies WDK
Documentation](https://docs.google.com/document/u/1/d/1nZayjR-0Hj3YeukjfwoWZ3TzokuuuWvSwnhw_q41oeE/pub).

Dependencies are managed with [yarn](https://yarnpkg.com/).

Tests are written for the [jest](https://jestjs.io/) testing framework.

=== Local Development

First, configure your local development environment by adding a `.env` file in `OrthoMCLClient/Site`. (We have provided a sample config in `.env.sample`.)

Next, install dependencies from npm:

[source, sh]
----
yarn install
----

Finally, start the dev server:

[source, sh]
----
yarn start
----
